# Server Configuration
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-16889bf8-pksathsara2001-b371.a.aivencloud.com:16842/defaultdb?allowPublicKeyRetrieval=true&useSSL=true&sslMode=REQUIRED&serverTimezone=Asia/Colombo}
spring.datasource.connectionProperties=useLegacyDatetimeCode=false;serverTimezone=Asia/Colombo
spring.datasource.hikari.connection-init-sql=SET time_zone = '+05:30';
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Colombo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Brevo SMTP Relay
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

# Security
spring.security.user.name=${ADMIN_USERNAME:admin}
spring.security.user.password=${ADMIN_PASSWORD:admin}

spring.jackson.time-zone=Asia/Colombo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

carereach.mail.sender=${MAIL_SENDER:carereach.official@gmail.com}