package com.carereach.backend.services;

import com.carereach.backend.dtos.PasswordUpdateDto;
import com.carereach.backend.dtos.UserProfileDto;
import com.carereach.backend.dtos.UserProfileUpdateDto;
import com.carereach.backend.dtos.UserRegistrationDto;
import com.carereach.backend.models.User;
import com.carereach.backend.repositories.UserRepository;
import com.carereach.backend.repositories.PatientRepository;
import com.carereach.backend.models.Patient;
import com.carereach.backend.models.DoctorCareer;
import com.carereach.backend.repositories.DoctorCareerRepository;
import java.util.Optional;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class UserService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private PatientRepository patientRepository;

    @Autowired
    private DoctorCareerRepository doctorCareerRepository;

    @Autowired
    private com.carereach.backend.repositories.NotificationRepository notificationRepository;

    @Autowired
    private NotificationService notificationService;

    @Autowired
    private EmailService emailService;

    public User registerUser(UserRegistrationDto registrationDto) {
        // Simple duplicate checks
        if (userRepository.findByEmail(registrationDto.getEmail()).isPresent()) {
            throw new RuntimeException("Email is already registered!");
        }

        if (userRepository.findByUsername(registrationDto.getUsername()).isPresent()) {
            throw new RuntimeException("Username is already taken!");
        }

        if (registrationDto.getNic() != null && !registrationDto.getNic().isEmpty() &&
                userRepository.findByNic(registrationDto.getNic()).isPresent()) {
            throw new RuntimeException("NIC is already registered!");
        }

        User newUser = new User();
        String finalName = registrationDto.getFullName();
        if (finalName == null || finalName.trim().isEmpty()) {
            finalName = registrationDto.getFirstName() + " " + registrationDto.getLastName();
        }
        newUser.setFullName(finalName);
        String generatedUsername = registrationDto.getUsername();
        if (generatedUsername == null || generatedUsername.trim().isEmpty()) {
            generatedUsername = "admin_" + java.util.UUID.randomUUID().toString().substring(0, 6);
        }

        String generatedPassword = registrationDto.getPassword();
        boolean isPasswordAutoGenerated = false;
        if (generatedPassword == null || generatedPassword.trim().isEmpty()) {
            generatedPassword = java.util.UUID.randomUUID().toString().substring(0, 12);
            isPasswordAutoGenerated = true;
        }

        newUser.setUsername(generatedUsername);
        newUser.setEmail(registrationDto.getEmail());
        newUser.setNic(registrationDto.getNic());
        newUser.setPhone(registrationDto.getPhone());
        newUser.setAddress(registrationDto.getAddress());
        newUser.setDistrict(registrationDto.getDistrict());
        newUser.setDivisionalSecretariat(registrationDto.getDivisionalSecretariat());
        newUser.setGnDivision(registrationDto.getGnDivision());
        newUser.setRole(registrationDto.getRole());

        // Save password plain for now (later use BCrypt)
        newUser.setPassword(generatedPassword);
        // Ensure the user is forced to reset login credentials initially ONLY if system
        // generated
        newUser.setRequiresCredentialReset(isPasswordAutoGenerated);

        User savedUser = userRepository.save(newUser);

        // Update Patient hasAccount flag if this is a PATIENT role
        if (savedUser.getRole() == com.carereach.backend.models.Role.PATIENT) {
            Optional<Patient> optPatient = Optional.empty();
            if (registrationDto.getPatientId() != null) {
                optPatient = patientRepository.findById(registrationDto.getPatientId().longValue());
            } else if (savedUser.getNic() != null && !savedUser.getNic().isEmpty()) {
                optPatient = patientRepository.findByNic(savedUser.getNic());
            }

            if (optPatient.isPresent()) {
                Patient pt = optPatient.get();
                pt.setHasAccount(true);
                patientRepository.save(pt);
            }
        } else if (savedUser.getRole() == com.carereach.backend.models.Role.GUARDIAN
                && registrationDto.getPatientId() != null) {
            Optional<Patient> optPatient = patientRepository.findById(registrationDto.getPatientId().longValue());
            if (optPatient.isPresent()) {
                Patient pt = optPatient.get();
                pt.setHasGuardianAccount(true);
                patientRepository.save(pt);
            }
        } else if (savedUser.getRole() == com.carereach.backend.models.Role.DOCTOR) {
            DoctorCareer career = new DoctorCareer();
            career.setUserId(savedUser.getId());
            career.setSpecialization(
                    registrationDto.getSpecialization() != null ? registrationDto.getSpecialization() : "General");
            career.setHospitalName(registrationDto.getHospitalName() != null ? registrationDto.getHospitalName()
                    : "CareReach Default");
            career.setQualification(
                    registrationDto.getQualification() != null ? registrationDto.getQualification() : "MBBS");
            career.setExperienceYears(
                    registrationDto.getExperienceYears() != null ? registrationDto.getExperienceYears() : 0);
            doctorCareerRepository.save(career);
        }

        // Dispatch the appropriate email
        String properRoleName = savedUser.getRole().name().substring(0, 1).toUpperCase()
                + savedUser.getRole().name().substring(1).toLowerCase();

        if (isPasswordAutoGenerated) {
            emailService.sendProvisioningEmail(savedUser.getEmail(), savedUser.getFullName(), generatedUsername,
                    generatedPassword, properRoleName);
        } else {
            emailService.sendWelcomeEmail(savedUser.getEmail(), savedUser.getFullName(), properRoleName);
        }

        return savedUser;
    }

    public User authenticateUser(String username, String password) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new RuntimeException("Invalid username or password!"));

        // Plain text comparison for now
        if (!user.getPassword().equals(password)) {
            throw new RuntimeException("Invalid username or password!");
        }

        return user;
    }

    public UserProfileDto getUserProfile(Long userId) {
        if (userId == null) {
            throw new IllegalArgumentException("User ID cannot be null");
        }
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found!"));

        UserProfileDto dto = new UserProfileDto();
        dto.setId(user.getId());
        dto.setFullName(user.getFullName());
        dto.setUsername(user.getUsername());
        dto.setEmail(user.getEmail());
        dto.setNic(user.getNic());
        dto.setPhone(user.getPhone());
        dto.setAddress(user.getAddress());
        dto.setRole(user.getRole().name());
        dto.setProfilePhoto(user.getProfilePhoto());

        Optional<DoctorCareer> optCareer = doctorCareerRepository.findByUserId(userId);
        if (optCareer.isPresent()) {
            dto.setSpecialistCategory(optCareer.get().getSpecialization());
            dto.setHospitalName(optCareer.get().getHospitalName());
            dto.setQualification(optCareer.get().getQualification());
            dto.setExperienceYears(optCareer.get().getExperienceYears());
        }

        dto.setDistrict(user.getDistrict());
        dto.setDivisionalSecretariat(user.getDivisionalSecretariat());
        dto.setGnDivision(user.getGnDivision());
        return dto;
    }

    public UserProfileDto updateUserProfile(Long userId, UserProfileUpdateDto updateDto) {
        if (userId == null) {
            throw new IllegalArgumentException("User ID cannot be null");
        }
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found!"));

        user.setFullName(updateDto.getFullName());
        if (updateDto.getUsername() != null && !updateDto.getUsername().isEmpty()) {
            String sanitizedUsername = updateDto.getUsername().trim();
            if (userRepository.existsByUsernameAndIdNot(sanitizedUsername, userId)) {
                throw new RuntimeException("Username is already taken!");
            }
            user.setUsername(sanitizedUsername);
        }

        // We handle email update below with the oldEmail state capture
        user.setPhone(updateDto.getPhone());
        user.setAddress(updateDto.getAddress());

        if (updateDto.getNic() != null) {
            user.setNic(updateDto.getNic());
        }
        if (updateDto.getGnDivision() != null) {
            user.setGnDivision(updateDto.getGnDivision());
        }

        if (user.getRole() == com.carereach.backend.models.Role.DOCTOR) {
            DoctorCareer career = doctorCareerRepository.findByUserId(userId).orElse(new DoctorCareer());
            career.setUserId(userId);

            if (updateDto.getSpecialistCategory() != null)
                career.setSpecialization(updateDto.getSpecialistCategory());
            if (updateDto.getHospitalName() != null)
                career.setHospitalName(updateDto.getHospitalName());
            if (updateDto.getQualification() != null)
                career.setQualification(updateDto.getQualification());
            if (updateDto.getExperienceYears() != null)
                career.setExperienceYears(updateDto.getExperienceYears());

            if (career.getSpecialization() == null)
                career.setSpecialization("");
            if (career.getHospitalName() == null)
                career.setHospitalName("");
            if (career.getQualification() == null)
                career.setQualification("");
            if (career.getExperienceYears() == null)
                career.setExperienceYears(0);

            doctorCareerRepository.save(career);
        }

        if (updateDto.getProfilePhoto() != null) {
            user.setProfilePhoto(updateDto.getProfilePhoto());
        }

        String oldEmail = user.getEmail();
        user.setEmail(updateDto.getEmail());

        User updatedUser = userRepository.save(user);

        // If Guardian's email changed, cascade it to the Linked Patients
        if (updatedUser.getRole() == com.carereach.backend.models.Role.GUARDIAN &&
                updateDto.getEmail() != null && !updateDto.getEmail().equals(oldEmail) && oldEmail != null) {
            List<Patient> linkedPatients = patientRepository.findByGuardianEmail(oldEmail);
            if (linkedPatients != null && !linkedPatients.isEmpty()) {
                for (Patient p : linkedPatients) {
                    p.setGuardianEmail(updatedUser.getEmail());
                }
                patientRepository.saveAll(linkedPatients);
            }
        }

        notificationService.createNotification(updatedUser.getId(), "Your profile was successfully updated.",
                "SUCCESS");

        return getUserProfile(updatedUser.getId());
    }

    public void requestPasswordResetOtp(Long userId, String currentPassword) {
        if (userId == null)
            throw new IllegalArgumentException("User ID cannot be null");
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found!"));

        if (!user.getPassword().equals(currentPassword)) {
            throw new RuntimeException("Incorrect current password!");
        }

        try {
            java.security.SecureRandom random = new java.security.SecureRandom();
            String otpCode = String.format("%06d", random.nextInt(1000000));

            user.setResetOtpCode(otpCode);
            user.setResetOtpExpiry(java.time.LocalDateTime.now().plusMinutes(5));
            userRepository.save(user);

            emailService.sendOtpVerificationEmail(user.getEmail(), otpCode);
            notificationService.createNotification(user.getId(), "A password reset code was dispatched to your email.",
                    "INFO");
        } catch (Exception e) {
            throw new RuntimeException("Error processing OTP request: " + e.getMessage());
        }
    }

    public void requestPublicPasswordResetOtp(String email) {
        if (email == null || email.trim().isEmpty())
            throw new IllegalArgumentException("Email cannot be empty");
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("No account found with this email"));

        try {
            java.security.SecureRandom random = new java.security.SecureRandom();
            String otpCode = String.format("%06d", random.nextInt(1000000));

            user.setResetOtpCode(otpCode);
            user.setResetOtpExpiry(java.time.LocalDateTime.now().plusMinutes(5));
            userRepository.save(user);

            emailService.sendOtpVerificationEmail(user.getEmail(), otpCode);
        } catch (Exception e) {
            throw new RuntimeException("Error dispatching OTP: " + e.getMessage());
        }
    }

    public void verifyAndResetPublicPassword(String email, String otpCode, String newPassword) {
        User user = userRepository.findByEmail(email).orElseThrow(() -> new RuntimeException("Invalid email"));

        if (user.getResetOtpCode() == null || !user.getResetOtpCode().equals(otpCode)) {
            throw new RuntimeException("Invalid OTP code!");
        }

        if (user.getResetOtpExpiry() == null || java.time.LocalDateTime.now().isAfter(user.getResetOtpExpiry())) {
            throw new RuntimeException("OTP expired!");
        }

        if (user.getPassword() != null && user.getPassword().equals(newPassword)) {
            throw new RuntimeException("New password cannot be the same as your old password!");
        }

        user.setPassword(newPassword);
        user.setResetOtpCode(null);
        user.setResetOtpExpiry(null);
        userRepository.save(user);
    }

    public void updateUserPassword(Long userId, PasswordUpdateDto passwordDto) {
        if (userId == null) {
            throw new IllegalArgumentException("User ID cannot be null");
        }
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found!"));

        if (!user.getPassword().equals(passwordDto.getCurrentPassword())) {
            throw new RuntimeException("Current password does not match!");
        }

        if (passwordDto.getOtpCode() == null || passwordDto.getOtpCode().isEmpty()) {
            throw new RuntimeException("OTP code is required!");
        }

        if (user.getResetOtpExpiry() == null || java.time.LocalDateTime.now().isAfter(user.getResetOtpExpiry())) {
            throw new RuntimeException("OTP code has expired. Please request a new one.");
        }

        if (!passwordDto.getOtpCode().equals(user.getResetOtpCode())) {
            throw new RuntimeException("Invalid OTP code!");
        }

        user.setPassword(passwordDto.getNewPassword());
        user.setResetOtpCode(null);
        user.setResetOtpExpiry(null);
        userRepository.save(user);

        notificationService.createNotification(user.getId(), "Your password was successfully changed.", "WARNING");
    }

    public void updateProfilePhoto(Long userId, String photoUrl) {
        if (userId == null) {
            throw new IllegalArgumentException("User ID cannot be null");
        }
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found!"));
        user.setProfilePhoto(photoUrl);
        userRepository.save(user);

        notificationService.createNotification(user.getId(), "Your profile photo was successfully updated.", "SUCCESS");
    }

    @org.springframework.transaction.annotation.Transactional
    public void deleteUser(Long userId) {
        if (userId == null) {
            throw new IllegalArgumentException("User ID cannot be null");
        }
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found!"));

        // Delete related doctor career if applicable
        if (user.getRole() == com.carereach.backend.models.Role.DOCTOR) {
            doctorCareerRepository.findByUserId(userId).ifPresent(career -> {
                doctorCareerRepository.delete(career);
            });
        }

        // Wipe any targeted notifications to prevent constraint failures
        notificationRepository.deleteAllByTargetUser_Id(userId);

        // Detach from patients (if they were a volunteer who reported patients)
        java.util.List<Patient> reportedPatients = patientRepository.findAllByReportedByIdOrderByIdDesc(userId);
        for (Patient p : reportedPatients) {
            p.setReportedBy(null);
        }
        patientRepository.saveAll((Iterable<Patient>) reportedPatients);

        userRepository.delete(user);
    }

    public boolean forceResetCredentials(Long userId, String newUsername, String newPassword) {
        if (userId == null) {
            throw new IllegalArgumentException("User ID cannot be null");
        }
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found!"));

        if (!user.isRequiresCredentialReset()) {
            throw new RuntimeException("This user does not require a credential reset.");
        }

        // Validate username uniqueness if changed
        if (!user.getUsername().equals(newUsername)) {
            if (userRepository.findByUsername(newUsername).isPresent()) {
                throw new RuntimeException("Username is already taken!");
            }
        }

        user.setUsername(newUsername);
        user.setPassword(newPassword);
        user.setRequiresCredentialReset(false);
        userRepository.save(user);

        notificationService.createNotification(user.getId(), "Your system credentials have been safely personalized.",
                "SUCCESS");
        return true;
    }
}
